spring:
    datasource:
        platform: mysql
        testWhileIdle: true
        url: jdbc:mysql://localhost:3306/proba?useSSL=false&useTimezone=true&serverTimezone=UTC
        username: vampirec
        password: password
#        validationQuery: SELECT 1
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        generate-ddl: true
        hibernate:
            ddl-auto: update
        show-sql: true
