spring:
    datasource:
        password: coderslab
        platform: mysql
        testWhileIdle: true
        url: jdbc:mysql://localhost:3306/beskidy?useSSL=false&useTimezone=true&serverTimezone=UTC
        username: root
        validationQuery: SELECT 1
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        generate-ddl: true
        hibernate:
            ddl-auto: update
        show-sql: true
